### ISSUE TITLE
在vue项目引入

### ISSUE THREAD

**Issue by gangmon** [junruchen/egg-obs#1]
new Error("Cannot find module 'egg-obs'"); e.code = 'MODULE_NOT_FOUND'; throw e;
安装后无法找到模块，这个应该怎么解决

**Comment by junruchen** [comment]
抱歉，这是针对egg的包，并不是针对vue框架的～

**Comment by junruchen** [comment]
> new Error("Cannot find module 'egg-obs'"); e.code = 'MODULE_NOT_FOUND'; throw e;
> 安装后无法找到模块，这个应该怎么解决

抱歉，这是针对Node egg.js框架的包，并不是针对vue的～

**Comment by gangmon** [comment]
如果vue项目想要前端直传，有解决方案吗？

**Comment by junruchen** [comment]
> 如果vue项目想要前端直传，有解决方案吗？

那你应该使用[BroswerJS SDK](https://support.huaweicloud.com/sdk-browserjs-devg-obs/zh-cn_topic_0125029729.html), 根据ID密钥初始化后，直接使用putObject上传到对应的桶即可。

**Comment by gangmon** [comment]
可以使用ajax上传文件到OBS吗，ID密钥放到formData中？
